---
title: 'Eccezioni: Funzione failwith'
description: Informazioni sul modo in cui la funzione ' failwith F# ' genera un'eccezione.
ms.date: 05/16/2016
ms.openlocfilehash: f2c86362d5bdde7bab55751f019965a5f4ca6236
ms.sourcegitcommit: f20dd18dbcf2275513281f5d9ad7ece6a62644b4
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 07/30/2019
ms.locfileid: "68630334"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="370ad-103">Eccezioni: Funzione failwith</span><span class="sxs-lookup"><span data-stu-id="370ad-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="370ad-104">La `failwith` funzione genera un' F# eccezione.</span><span class="sxs-lookup"><span data-stu-id="370ad-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="370ad-105">Sintassi</span><span class="sxs-lookup"><span data-stu-id="370ad-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="370ad-106">Note</span><span class="sxs-lookup"><span data-stu-id="370ad-106">Remarks</span></span>

<span data-ttu-id="370ad-107">La *stringa di messaggio di errore* nella sintassi precedente è una stringa letterale o un valore di tipo `string`.</span><span class="sxs-lookup"><span data-stu-id="370ad-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="370ad-108">Diventa la `Message` proprietà dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="370ad-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="370ad-109">L' `failwith` eccezione generata da è un' `System.Exception` eccezione, ovvero un riferimento con il nome `Failure` nel F# codice.</span><span class="sxs-lookup"><span data-stu-id="370ad-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="370ad-110">Il codice seguente illustra l'uso di `failwith` per generare un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="370ad-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](~/samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="370ad-111">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="370ad-111">See also</span></span>

- [<span data-ttu-id="370ad-112">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="370ad-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="370ad-113">Tipi di eccezione</span><span class="sxs-lookup"><span data-stu-id="370ad-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="370ad-114">Eccezioni: `try...with` Espressione</span><span class="sxs-lookup"><span data-stu-id="370ad-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="370ad-115">Eccezioni: `try...finally` Espressione</span><span class="sxs-lookup"><span data-stu-id="370ad-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="370ad-116">Eccezioni: funzione `raise`</span><span class="sxs-lookup"><span data-stu-id="370ad-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
